name: Build with ESP-IDF v4.4

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Patch BTstack
      shell: bash
      run: cd external/btstack && git apply ../patches/*.patch

    - name: Install BTstack
      shell: bash
      run: cd external/btstack/port/esp32 && IDF_PATH=../../../../src/ ./integrate_btstack.py

    - name: Unijoysticle build
      uses: espressif/esp-idf-ci-action@main
      with:
        esp_idf_version: release-v4.4
        target: esp32
        path: 'src'
        # Χρησιμοποιούμε το συγκεκριμένο sdkconfig που ζήτησες
        command: 'idf.py -B build_unijoysticle -D SDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.ci.plat_unijoysticle" build'

    - name: Upload Unijoysticle Artifact
      uses: actions/upload-artifact@v4
      with:
        name: unijoysticle-binary
        path: src/build_unijoysticle/**/*.bin
        if-no-files-found: error
